services:
  postgres:
    container_name: orderflow_container
    image: postgres:18
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: orderflow
      POSTGRES_PASSWORD: TROUBADOR!
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
volumes:
  pgdata: