version: '4.1'
services:
  java_app:
    container_name: orderflow_app
    image: orderflow-java_app
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - java_db

  java_db:
    container_name: orderflow_container
    image: postgres:18
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: orderflow
      POSTGRES_PASSWORD: TROUBADOR!
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
volumes:
  pgdata: