spring.application.name=orderflow

spring.datasource.url=jdbc:postgresql://java_db:5432/orderflow
spring.datasource.username=postgres
spring.datasource.password=TROUBADOR!

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

management.endpoints.web.base-path=/details
management.endpoint.metrics.enabled=true
management.endpoints.web.exposure.include=metrics,info