spring.application.name=orderflow

spring.datasource.url=jdbc:postgresql://java_db:5432/orderflow
spring.datasource.username=postgres
spring.datasource.password=TROUBADOR!

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true